defaults: &defaults
  adapter: mysql2
  host: 127.0.0.1
  encoding: utf8
  username: root
  password: root
  pool: 12

development:
  <<: *defaults
  database: tiantian_development

production:
  <<: *defaults
  database: tiantian_production

test: &test
  <<: *defaults
  database: tiantian_test

